#ifndef EMOJI_H
# define EMOJI_H

# define 🌠 void
# define 🔢 int
# define 🔤 char
# define 💯 double
# define ✨ float
# define 📏 long
# define 🏷️ short
# define 🎯 bool
# define 🔄 for
# define ⏳ while
# define 🎬 if
# define 🎭 else
# define 🔀 switch
# define 📋 case
# define 🚪 break
# define ⏭️ continue
# define 🎪 do
# define 🔚 return
# define 📢 printf
# define 📥 scanf
# define 📖 gets
# define 📝 puts
# define 💾 malloc
# define 🗑️ free
# define 📊 sizeof
# define 🔗 include
# define 🟰 ==
# define 🚫 !=
# define ⬆️ >
# define ⬇️ <
# define ⬆️🟰 >=
# define ⬇️🟰 <=
# define ➕ +
# define ➖ -
# define ✖️ *
# define ➗ /
# define 🔁 %
# define 🤝 &&
# define 🤷 ||
# define ❗ !
# define 👉 *
# define 🏠 &
# define 🌟 const
# define 🔒 static
# define 🌍 extern
# define 🏗️ struct
# define 🏷️📦 typedef
# define 🔗📦 union
# define 🎯📋 enum
# define 💀 NULL
# define ✅ 1
# define ❌ 0
# define 🆔 '\0'
# define 📁 FILE
# define 📂 fopen
# define 🔐 fclose
# define 📄 fread
# define ✍️ fwrite
# define 📍 fseek
# define 🔤📏 strlen
# define 🔤📋 strcpy
# define 🔤🔗 strcat
# define 🔤🔍 strcmp
# define 🥧 3.14159265359
# define 🎯🌟 #define
# define 📚 #include
# define 🚀 main
# define 🎪🔚 return 0;
#endif
